# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sumber
import sys


class Ui_show_login(object):
    def setupUi(self, show_login):
        show_login.setObjectName("show_login")
        show_login.resize(618, 531)
        ####################################
        show_login.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        show_login.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        ###################################
        self.centralwidget = QtWidgets.QWidget(show_login)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 571, 491))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(280, 40, 251, 421))
        self.label.setStyleSheet("border-image: url(:/png/gambarpng 1.png);\n"
"border-bottom-right-radius : 50px\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 261, 421))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0508475, y1:0.813, x2:0.944, y2:0.0511364, stop:0 rgba(0, 11, 114, 255), stop:1 rgba(196, 255, 255, 255));\n"
"border-top-left-radius : 50px\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(110, 100, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.t_login = QtWidgets.QToolButton(self.widget)
        self.t_login.setGeometry(QtCore.QRect(70, 340, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.t_login.setFont(font)
        #########################################
        self.t_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        ########################################
        self.t_login.setStyleSheet("QToolButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.0508475, y1:0.983, x2:0.944, y2:0.0511364, stop:0 rgba(0, 50, 59, 255), stop:1 rgba(71, 255, 255, 255));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.t_login.setObjectName("t_login")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(70, 185, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(70, 250, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.exit = QtWidgets.QToolButton(self.widget)
        self.exit.setGeometry(QtCore.QRect(530, 20, 25, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        #########################################
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        #########################################
        self.exit.setStyleSheet("QToolButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0.0508475, y1:0.983, x2:0.944, y2:0.0511364, stop:0 rgba(0, 50, 59, 255), stop:1 rgba(71, 255, 255, 255));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.exit.setObjectName("exit")
        self.exit.clicked.connect(sys.exit)##########################
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.t_login.raise_()
        self.username.raise_()
        self.password.raise_()
        self.exit.raise_()
        show_login.setCentralWidget(self.centralwidget)

        #############################################
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset = 0 , yOffset = 0, color = QtGui.QColor(234,221,186,100)))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset = 0 , yOffset = 0, color = QtGui.QColor(105,118,132,100)))
        self.label_4.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset = 0 , yOffset = 0, color = QtGui.QColor(105,118,132,100)))
        self.t_login.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset = 0 , yOffset = 0, color = QtGui.QColor(105,118,132,100)))
        self.exit.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius = 25 , xOffset = 0 , yOffset = 0, color = QtGui.QColor(234,221,186,100)))
        #############################################

        self.retranslateUi(show_login)
        QtCore.QMetaObject.connectSlotsByName(show_login)

    def retranslateUi(self, show_login):
        _translate = QtCore.QCoreApplication.translate
        show_login.setWindowTitle(_translate("show_login", "Login"))
        self.label_4.setText(_translate("show_login", "Log In"))
        self.t_login.setText(_translate("show_login", "L o g  I n"))
        self.username.setPlaceholderText(_translate("show_login", "Username"))
        self.password.setPlaceholderText(_translate("show_login", "Password"))
        self.exit.setText(_translate("show_login", "X"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    show_login = QtWidgets.QMainWindow()
    ui = Ui_show_login()
    ui.setupUi(show_login)
    show_login.show()
    sys.exit(app.exec_())
